import swaggerJsdoc from 'swagger-jsdoc';
import config from './index';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'CEM Modular Express API',
      version: '1.0.0',
      description:
        'Interactive OpenAPI 3.0 documentation generated by Create Express Modular CLI.',
    },
    servers: [
      {
        url: `http://localhost:${config.port}/api/v1`,
        description: 'Development Server',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
    },
  },
  apis: [
    './src/app/modules/**/*.route.ts',
    './src/app/modules/**/*.controller.ts',
  ],
};

export const swaggerSpec = swaggerJsdoc(options);
